spring:
  datasource:
    url: jdbc:h2:mem:finance_tm_db;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: lucas
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: America/Sao_Paulo
spring.h2.console:
  enabled: true
  path: /h2-console
logging:
  level:
    org.hibernate.SQL: debug
